CREATE database MENUSYSTEM;
USE MENUSYSTEM;

CREATE TABLE COMPANYS(
CNPJ VARCHAR(20) PRIMARY KEY NOT NULL,
COMPANY_NAME VARCHAR(50) NOT NULL
);



CREATE TABLE PRODUCTS(
IDPRODUCT INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
PRODUCT_NAME VARCHAR(40) NOT NULL,
DESCRIPTION VARCHAR(80) NOT NULL,
PRICE FLOAT NOT NULL,
CNPJ VARCHAR(20) NOT NULL,
FOREIGN KEY (CNPJ) REFERENCES COMPANYS(CNPJ)
);

CREATE TABLE USERS(
IDUSER INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
NAME VARCHAR(40) NOT NULL,
SENHA VARCHAR(40) NOT NULL,
CNPJ VARCHAR(20) NOT NULL,
ADMIN SMALLINT NOT NULL,
FOREIGN KEY (CNPJ) REFERENCES COMPANYS(CNPJ)
);

CREATE TABLE CHECKS(
CHECK_NUMBER INT PRIMARY KEY NOT NULL,
CNPJ VARCHAR(20) NOT NULL,
FOREIGN KEY (CNPJ) REFERENCES COMPANYS(CNPJ)
);

CREATE TABLE ORDERS(
IDORDER INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
CNPJ VARCHAR(20) NOT NULL,
TOTAL FLOAT NOT NULL,
ORDER_DATE DATETIME NOT NULL,
CHECK_NUMBER INT NOT NULL,
FOREIGN KEY (CHECK_NUMBER) REFERENCES CHECKS(CHECK_NUMBER),
FOREIGN KEY (CNPJ) REFERENCES COMPANYS(CNPJ)
);

CREATE TABLE ORDER_DETAILS(

IDORDER INT NOT NULL,
CNPJ VARCHAR(20) NOT NULL,
IDPRODUCT INT NOT NULL,
ITEM INT PRIMARY KEY NOT NULL,
CHECK_NUMBER INT NOT NULL,
PRICE FLOAT NOT NULL,
ORDER_DATE DATETIME NOT NULL,
FOREIGN KEY (IDORDER) REFERENCES ORDERS(IDORDER),
FOREIGN KEY (CNPJ) REFERENCES COMPANYS(CNPJ),
FOREIGN KEY (IDPRODUCT) REFERENCES PRODUCTS(IDPRODUCT),
FOREIGN KEY (CHECK_NUMBER) REFERENCES CHECKS(CHECK_NUMBER)

);




